### ISSUE TITLE
Wrong results when parsing big Ints

### ISSUE THREAD

**Issue by Chakerbh** [quinnj/JSON3.jl#124]
This can be reproduced with 
```
julia> JSON3.read("333333833333500000")
333333833333500032
```
The result of the parsing is wrong. I tracked it to this [part](https://github.com/quinnj/JSON3.jl/blob/master/src/read.jl#L70-L78) of the code and more specifically 
```
unsafe_trunc(Int64, 3.333338333335e17)
```

**Comment by quinnj** [comment]
Relevant info from the JSON spec:
```
This specification allows implementations to set limits on the range
   and precision of numbers accepted.  Since software that implements
   IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is
   generally available and widely used, good interoperability can be
   achieved by implementations that expect no more precision or range
   than these provide, in the sense that implementations will
   approximate JSON numbers within the expected precision.  A JSON
   number such as 1E400 or 3.141592653589793238462643383279 may indicate
   potential interoperability problems, since it suggests that the
   software that created it expects receiving software to have greater
   capabilities for numeric magnitude and precision than is widely
   available.

   Note that when such software is used, numbers that are integers and
   are in the range [-(2**53)+1, (2**53)-1] are interoperable in the
   sense that implementations will agree exactly on their numeric
   values.
```

**Comment by Chakerbh** [comment]
Thanks @quinnj for following up quickly.

So JSON3 follow the last paragraph of the spec to only support integer precision for unsigned 64bit?

**Comment by quinnj** [comment]
Sorry for not giving context; no, I think this is indeed a bug. If we're going to auto-convert numbers to Int64 at all (which can be a really nice property), we should at least do it accurately/correctly for valid Int64 numbers. I've got a PR up now that I think solves all the issues: https://github.com/quinnj/JSON3.jl/pull/125. But it'd be nice to document JSON3.jl's behavior on number parsing since it's kind of a fuzzy concept in the spec. For the record here at least, JSON3.jl can parse any Int64 integer accurately, and all other numbers will be parsed as Float64. That means for floats w/ greater than 53 bits of precision, the parsing will be lossy. But as noted in the spec above, it gives a general recommendation that implementations should at least handle Float64 and are probably best off making that the default. So we should at least be "in the norm" here, with a slight advantage that we can parse integer numbers w/ greater than 53-bits of precision exactly instead of only allowing a lossy Float64 for those.

It's also worth noting that this all only applies/effects the "typeless" reading; you _can_ parse arbitrary numbers if needed, by doing:
```julia
julia> JSON3.read("9223372036854775808", BigInt)
9223372036854775808

julia> typeof(ans)
BigInt
```
