### ISSUE TITLE
Support Optional/Missing fields for StructType

### ISSUE THREAD

**Issue by vchuravy** [quinnj/JSON3.jl#136]
```
struct System
    duration::Real
    cwd::Union{Nothing, String}
    environment::Union{Nothing, Dict}
   System(duration, cwd=nothing, environment=nothing) = new(duration, cwd, environment)
end
StructTypes.StructType(::Type{System}) = StructTypes.Struct()

let system = """
    {    
        "duration": 3600
    }
    """
    sys = JSON3.read(system, System)
    @assert sys.duration == 3600
end
```

fails with:

```
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex at ./array.jl:809 [inlined]
 [2] construct at /home/vchuravy/.julia/packages/StructTypes/MF8bN/src/StructTypes.jl:860 [inlined]
 [3] #read#42 at /home/vchuravy/.julia/packages/JSON3/IvnMR/src/structs.jl:572 [inlined]
 [4] read at /home/vchuravy/.julia/packages/JSON3/IvnMR/src/structs.jl:494 [inlined]
 [5] read(::String, ::Type{System}; kw::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/vchuravy/.julia/packages/JSON3/IvnMR/src/structs.jl:34
 [6] read(::String, ::Type{System}) at /home/vchuravy/.julia/packages/JSON3/IvnMR/src/structs.jl:33
 [7] top-level scope at REPL[6]:6
```

Additionally this fails similarly:
```
struct System
    duration::Real
    cwd::Union{Nothing, String}
    environment::Union{Nothing, Dict}
   System(duration, cwd=nothing, environment=nothing) = new(duration, cwd, environment)
end
StructTypes.StructType(::Type{System}) = StructTypes.Struct()
StructTypes.omitempties(::Type{System}) = (:cwd, :environment)

sys = JSON3.read(JSON3.write(System(3600)), System)
@assert sys.duration == 3600
```

**Comment by quinnj** [comment]
So the biggest question here is what would we do in the case where our json is like:
```json
{
    "duration": 3600,
    "environment": {"PATH": "/usr/lib"}
}
```
It makes me squirm a little to say we'd just end up calling `System(duration, environment)` because that could quickly cause weird issues for people if htey have a struct like:
```julia
struct T
    id::Int
    fname::String
    lname::String
end
```
where `fname` is missing from the json. But I'm also not excited about the alternative of just ignoring any fields after the first `#undef`.

Hmmmm, what to do, what to do. We've talked at one point about having a `StructTypes.defaultvalues` overload where default values could be provided for missing fields; maybe that's the solution here.

**Comment by olynch** [comment]
I just ran into this exact problem.

**Comment by quinnj** [comment]
Yeah, I guess this change is really a bug from the `StructTypes.Struct => StructTypes.UnorderedStruct` change, because the behavior before was that it would pass any arguments parsed in order ot the constructor. Hmmm, unfortunately that's quite at odds with the current code implementation where it's trying to put the fields in order. Let me stew on if we can get the old behavior here again.

**Comment by quinnj** [comment]
Ok, here's a proposed alternative fix that wouldn't incur any performance hit: if a field wasn't found when parsing, we pass `nothing`. This is somewhat accurate, since `nothing` maps to the JSON `null` value, and it's often standard JSON to either _include_ the field with `null` value or omit the field entirely. So we'll just flip that coin when constructing: parse values, pass them in _field_ order to the constructor, if any field has a `null` field, it would be passed as `nothing`, if it's omitted from the parsing, we still pass `nothing`. How does that sound?

**Comment by quinnj** [comment]
Ok, PR up if anyone cares to take a look: https://github.com/JuliaData/StructTypes.jl/pull/43
