### ISSUE TITLE
Add "Getting Started" section to docs

### ISSUE THREAD

**Issue by mcmcgrath13** [quinnj/JSON3.jl#146]
* read/write API
* basic examples
* maybe a section on why JSON3 vs others
* anything else? (@quinnj )

**Comment by quinnj** [comment]
Those all sound great to me!

**Comment by RicardoHS** [comment]
I was about to open a similar issue. I am finding it impossible to start using the library.

**Comment by quinnj** [comment]
@RicardoHS, can you share more what's so difficult? For plain reading/writing, it's just `JSON3.write(x)`, `JSON3.read(json)`. For type-specific reading, you just need to define the appropriate `StructTypes.StructType` trait, then `JSON3.read(json, Tj)`.

**Comment by RicardoHS** [comment]
It is probably because I am new to Julia and have not yet mastered the typing system. In any case, I have doubts if the solution I have built is the optimal one. Here is a json example:

```json
{"id":2928883026,
"l1":[["0.03932500","12.03100000"],["0.03932400","1.47100000"]],
"l2":[["0.03932600","8.46800000"],["0.03932700","3.89300000"]]
}
```
So I tried to read it with this code

```julia
struct JsonStructure
    id::Integer
    l1::Vector{Vector{Any}}
    l2::Vector{Vector{Any}}
end

StructTypes.StructType(::Type{JsonStructure}) = StructTypes.Struct()

request = HTTP.request("GET", url)
response = JSON3.read(request.body, JsonStructure)
```

That code gives me this error `ERROR: MethodError: no method matching typemax(::Type{Integer})`. So I change the struct.id type to Int64 and it works (doesn't know why). My final code is this one, but I don't know if it is optimal or even if there is a way to tell JSON3 to automatically cast the String types to Float64 (in case not I think it would be a great feature)

```julia
struct JsonStructure
    id::Int64
    l1::Vector{Vector{String}}
    l2::Vector{Vector{String}}
end

StructTypes.StructType(::Type{JsonStructure}) = StructTypes.Struct()

request = HTTP.request("GET", url)
response = JSON3.read(request.body, JsonStructure)
```

**Comment by quinnj** [comment]
> That code gives me this error ERROR: MethodError: no method matching typemax(::Type{Integer})

Ah, so this error is because `Integer` in Julia is an _abstract_ type, not concrete, like `Int64`. For JSON3.jl, it almost always needs concrete types in order to know what kind of "thing" to parse/create.

`JSON3.read` supports a keyword argument `parsequoted=true`, which allows treating your floats-as-strings as regular numbers. So your use-case would become:
```julia
struct JsonStructure
    id::Int64
    l1::Vector{Vector{Float64}}
    l2::Vector{Vector{Float64}}
end

StructTypes.StructType(::Type{JsonStructure}) = StructTypes.Struct()

request = HTTP.request("GET", url)
response = JSON3.read(request.body, JsonStructure; parsequoted=true)
```

**Comment by RicardoHS** [comment]
Thank you very much for the explanation.

This kind of examples are the ones that could be cool for the getting started section.

**Comment by mcmcgrath13** [comment]
I started the PR for the docs.  Take a look to see what doesn't quite make sense or is missing.
