### ISSUE TITLE
Parsing into a Union

### ISSUE THREAD

**Issue by wmanning-cra** [quinnj/JSON3.jl#172]
It would be really helpful if a value that is a union of two types could be parsed correctly.

For example:

````
@assert(JSON3.read("true", Union{Bool, Int}))
# Result: ERROR: ArgumentError: invalid JSON at byte position 1
#                  while parsing type Union{Bool, Int64}: InvalidChar

i::Int = JSON3.read("42", Union{Bool, Int})
# Result: ERROR: MethodError: no method matching
#                  Union{Bool, Int64}(::UInt8)
````

**Comment by quinnj** [comment]
Ah shoot, this is because `Bool <: Integer`, so the `StructTypes.StructType(Union{Bool, Int}) == StructTypes.NumberType()`. Hmmmm.....we'll have to see if we can figure this out. Typically `JSON3.read` should handle reading Unions otherwise.

**Comment by quinnj** [comment]
Ok, ended up not being too bad of a fix: https://github.com/quinnj/JSON3.jl/pull/174. I considered whether we should have a definition in StructTypes.jl like `StructTypes.StructType(::Type{Union{Bool, T}}) where {T <: Real} = StructTypes.Struct()`, but it seems like the `Union` problem in this issue is fairly specific to the json format, where bools and numbers have distinct representations. In Julia, however, they're similar enough to inherit a lot of the same behavior, so I don't think it's quite warranted that we'd treat them as totally separate for other users of StructTypes.jl
