### ISSUE TITLE
Slight incompatibility between LazyJSON.Object and JSON3.write

### ISSUE THREAD

**Issue by ninjaaron** [quinnj/JSON3.jl#21]
Hi! Thanks for JSON3 (and JSON2)!

```julia
julia> using LazyJSON, JSON3

julia> object = LazyJSON.value("""{"foo":"bar"}""")
LazyJSON.Object{Nothing,String} with 1 entry:
  "foo" => "bar"

julia> JSON3.write(object) |> println
{"\"foo\"":"bar"}

julia> JSON3.write(Dict("foo" => "bar")) |> println
{"foo":"bar"}
```
It's awesome that this even works at all, but as you can see, `LazyJSON.Object` keys somehow get extra quotes when printed. Since compatibility is already 99% there, it would be nice if this issue could be fixed. I don't know if the problem is on your end or LazyJSON's end, but I opened [an issue over there as well](https://github.com/JuliaCloud/LazyJSON.jl/issues/12).

**Comment by quinnj** [comment]
Hmmm, let me look into it. Thanks for reporting.

**Comment by quinnj** [comment]
Ok, looks like this is due to [this definition](https://github.com/JuliaCloud/LazyJSON.jl/blob/df4d4ab906d9dde3a1743795492a417c8bfaccd2/src/LazyJSON.jl#L73); basically, LazyJSON.jl defines `string(::JSON.Value)` to mean "give me a SubString back into the original json for this value", which in the case of an object key, includes the quotes I guess. Personally, I think that's a poor definition since `string(x)` has a generally accepted meaning of "give me the stringified version of `x`". It looks like LazyJSON also defines a `jsonstring`, which seems like it would be a more appropriate function name for what `string` is currently doing.

**Comment by ninjaaron** [comment]
Thanks for looking into it! I'll mention it on the issue on LazyJSON.

**Comment by ninjaaron** [comment]
Thanks for find that! I'll bring it up on the other issue.
