### ISSUE TITLE
integration with CategoricalArrays.jl

### ISSUE THREAD

**Issue by bkamins** [quinnj/JSON3.jl#27]
This happens:
```
┌ Warning: `ncodeunits(x::CategoricalString)` is deprecated, use `ncodeunits(String(x))` instead.
│   caller = write(::JSON3.StringType, ::Array{UInt8,1}, ::Int64, ::Int64, ::CategoricalString{UInt8}) at write.jl:251
└ @ JSON3 ~\.julia\packages\JSON3\phpk5\src\write.jl:251
┌ Warning: `ncodeunits(x::CategoricalString)` is deprecated, use `ncodeunits(String(x))` instead.
│   caller = macro expansion at simdloop.jl:69 [inlined]
└ @ Core .\simdloop.jl:69
┌ Warning: `codeunit(x::CategoricalString, i::Integer)` is deprecated, use `codeunit(String(x), i)` instead.
│   caller = macro expansion at write.jl:243 [inlined]
└ @ Core ~\.julia\packages\JSON3\phpk5\src\write.jl:243
┌ Warning: `codeunit(x::CategoricalString, i::Integer)` is deprecated, use `codeunit(String(x), i)` instead.
│   caller = macro expansion at write.jl:265 [inlined]
└ @ Core ~\.julia\packages\JSON3\phpk5\src\write.jl:265
```
when we write a `DataFrame` containing categorical strings.

@nalimilan - do we have to change this or with the next release of CategorcialArrays.jl this will be gone?

CC @quinnj

**Comment by nalimilan** [comment]
AFAICT that's an unfortunate consequence of `CategoricalString <: AbstractString`. We can't add a deprecation for that subtyping relation, so the solution I used is to print deprecation warnings for all functions in the `AbstractString` interface so that people notice.

I guess that's an argument in favor of making another breaking release relatively soon. That's too bad we can't leave more time for users to adapt...

**Comment by quinnj** [comment]
Yeah, CategoricalString needs to stop subtyping `AbstractString` since it doesnt' implement the interface, which JSON3 relies on.
