### ISSUE TITLE
Why are keys of a `Dict` not unpacked before serialization?

### ISSUE THREAD

**Issue by simsurace** [quinnj/JSON3.jl#286]
Is this intentional? Values of a dict are unpacked before serialization, but keys are not:
```julia
using JSON3, StructTypes

struct IntWrapper
    val::Int
end

StructTypes.StructType(::Type{IntWrapper}) = StructTypes.NumberType()
StructTypes.numbertype(::Type{IntWrapper}) = Int
Base.Int(id::IntWrapper) = id.val

JSON3.write(IntWrapper(42)) == "42" # true
JSON3.write(Dict(IntWrapper(42) => 42)) == "{\"42\":42}" # false
JSON3.write(Dict(42 => IntWrapper(42))) == "{\"42\":42}" # true
```
Am I missing something or is this a bug?

**Comment by Naunet** [comment]
JSON only allows string keys.

It would appear that the dictionary keys are indeed being unwrapped since the result is a string and not a structure. However they then get "stringified" to be acceptable keys. 

Some related discussions that may help you find a work-around:
- [Reading and writing is broken for `Dict`s with struct keys · Issue #71 · quinnj/JSON3.jl · GitHub 1](https://github.com/quinnj/JSON3.jl/issues/71)
- https://discourse.julialang.org/t/json3-read-dict-tuple-int-int-t-unexpected-behavior/117759

**Comment by quinnj** [comment]
Yeah, we have to ensure we produce valid JSON when writing

**Comment by simsurace** [comment]
Thanks, this makes sense!
