### ISSUE TITLE
Automatically skip all `nothing`s in a struct?

### ISSUE THREAD

**Issue by DilumAluthge** [quinnj/JSON3.jl#90]
I have a lot of structs that look like this:
```julia
mutable struct Foo
    field_1::Union{Some_Type_1, Nothing}
    field_2::Union{Some_Type_2, Nothing}
    # ...
    field_50::Union{Some_Type_50, Nothing}
end
```

I want to skip the writing of any field that is `nothing`. Currently, I can do this by listing out all of those fields and giving it to `StructTypes.omitempties`. But this gets tedious when I have so many structs that have so many fields.

Is there a more concise way to tell JSON3 to automatically apply `omitempties` to all fields in a struct?

**Comment by quinnj** [comment]
We could potentially allow defining `StructTypes.omitempties(::Type{MyType}) = true`, instead of spelling out the fields. That should have good inferability and we'd just need to update the various `construct`/`applyfields!` methods in StructTypes.jl to respect that. i.e. the logic would call `omitempties` and then omit if it was `=== true || fieldname in omits` (roughly speaking). If you want to take a stab at a PR to StructTypes.jl, feel free, or I can take a look at it in the next week or so.

**Comment by DilumAluthge** [comment]
https://github.com/JuliaData/StructTypes.jl/pull/19
